In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import geopandas as gpd


In [2]:
# function to load shapfiles in as a geopandas object
def load_shape_file(filepath):
    """Loads the shape file desired to mask a grid.
    Args:
        filepath: Path to *.shp file
    """
    shpfile = gpd.read_file(filepath)
    return shpfile

In [3]:
#RGV_ecoreg= Rio Grande Valley Ecoregions
RGV_ecoreg = load_shape_file('C:\Bridgett\Bridgett\Introduction to Scientific computing\Everything\RGV_Ecoregions\RGV_Ecoregions.shp')
RGV_ecoreg.head() # .head gives you the first few lines, aka shapes

OBJECTID  Veg_ID                                    CommonName  LULC  \
0         1    7004  South Texas: Clayey Mesquite Mixed Shrubland     5   
1         2    7004  South Texas: Clayey Mesquite Mixed Shrubland     5   
2         3    7004  South Texas: Clayey Mesquite Mixed Shrubland     5   
3         4    7004  South Texas: Clayey Mesquite Mixed Shrubland     5   
4         5    7004  South Texas: Clayey Mesquite Mixed Shrubland     5   

   Slope  Riparian   EcoClass_I                   EcoName  MoRAP_ID US_L4CODE  \
0      0         0  R083DY501TX  GRAY SANDY LOAM PE 19-31     40311       31c   
1      0         0  R083DY501TX  GRAY SANDY LOAM PE 19-31     40312       31c   
2      0         0  R083DY501TX  GRAY SANDY LOAM PE 19-31     40375       31c   
3      0         0  R083DY501TX  GRAY SANDY LOAM PE 19-31     40447       31c   
4      0         0  R083DY501TX  GRAY SANDY LOAM PE 19-31     40472       31c   

                     US_L4NAME US_L3CODE              US_L3NAME      HUC12RNG  \
0  Texas-Tamaulipan Thornscrub        31  Southern Texas Plains  121102080100   
1  Texas-Tamaulipan Thornscrub        31  Southern Texas Plains  121102080100   
2  Texas-Tamaulipan Thornscrub        31  Southern Texas Plains  121102080100   
3  Texas-Tamaulipan Thornscrub        31  Southern Texas Plains  121102080100   
4  Texas-Tamaulipan Thornscrub        31  Southern Texas Plains  121102080100   

   Shape_Leng  Shape_Area                                           geometry  
0   380.00000   2700.0000  POLYGON ((1653879 6904557, 1653869 6904557, 16...  
1   260.00000   1400.0000  POLYGON ((1652969 6904537, 1652969 6904587, 16...  
2   291.84704   1682.2225  POLYGON ((1655129 6903767.6097, 1655079 690377...  
3  1860.00000  36800.0000  POLYGON ((1656909 6903857, 1656899 6903857, 16...  
4   160.00000   1300.0000  POLYGON ((1656749 6903537, 1656749 6903517, 16...

In [4]:
#This list has the Veg_ID of all subecoregion types in the Maj ecoregion

#Tamaulipan Mixed Deciduous
TMDT=[7002,7004,7005]
#Tamaulipan Savanna Grassland
TSG=[7102,7103,7104,7105,7107]
#Tamaulipan Calcareous Thornscrub
TCS=[7202,7204,7205,7207]
#Tamaulipan Floodplain
TFP=[7402,7403,7404,7405,7406,7407,7417]
#Tamaulipan Ramadero
TR=[7602,7604,7605,7606]
#Agricultural and other Human-related Mapped Types
AOHR=[9304,9307,9410,9411]
#Tamaulipan Closed Depression Wetland
TCDW=[10004,10006]
#Texas Saline Coastal Prairie
TSCP=[2207,2206]
#Texas Coast Salt and Brackish Tidal Marsh
TCSBTM=[5600,5605,5606,5607,5616,5617]
#Texas Coast Dune and Coastal Grassland
TCDCG= [6200,6307,6306]
#Central and South Texas Coastal Fringe Forest and Woodland
CSTCFFW= [6402,6403,6405,6407]
#Southeastern Coastal Plain Interdunal Wetland
SECPIW= [6507]
#South Texas Salt and Brackish Tidal Flats
STSBTF=[6600,6610]
#Tamaulipan Lomas
TL=[7305,7306,7307]
#Tamaulipan Palm Grove Riparian Forest
TPGRF=[7502]
#Tamaulipan Saline Lake
TSL=[7700,7707]
#Barren
Barren=[9000]
#Marsh
Marsh=[9007]
#South Texas: Disturbance Grassland 
STDGL=[9187]
#Open Water
OW=[9600]
#Native Invasive
NI=[9104,9106,9124,9116]
#Non-native Invasive
NNI=[9204]

#Tamaulipan Saline Thornscrub
TSTS=[6806]

#Central and South Texas Coastal Fringe Forest and Woodland
CSTCFFW=[6402,6403]

#Tamaulipan Caliche Grassland
TCGL=[6707]

#10017, 7607 are not on the PDF

In [5]:
RGV_ecoreg['Major_Ecoregion'] = np.zeros
Maj_Eco = RGV_ecoreg['Major_Ecoregion']

In [6]:
df = []
Veg_ID = RGV_ecoreg['Veg_ID']

In [7]:
for i in Veg_ID:
    if i in TMDT:
        df.append('Tamaulipan Mixed Deciduous Thornscrub')
    elif i in TSG:
        df.append('Tamaulipan Savanna Grassland')
    elif i in TCS:
        df.append('Tamaulipan Calcareous Thornscrub')
    elif i in TFP:
        df.append('Tamaulipan Floodplain')
    elif i in TR:
        df.append('Tamulipan Ramadero')
    elif i in AOHR:
        df.append('Agricultural and Human-Related Types')
    elif i in TCDW:
        df.append('Tamaulipan Closed Depression Wetland')
    elif i in TSCP:
        df.append('Texas Saline Coastal Prairie')
    elif i in TCSBTM:
        df.append('Texas Coast Salt and Brackish Tidal Marsh')
    elif i in TCDCG:
        df.append('Texas Coast Dune and Coastal Grassland')
    elif i in CSTCFFW:
        df.append('Central and South Texas Coastal Fringe Forest and Woodland')
    elif i in SECPIW:
        df.append('Southeastern Coastal Plain Interdunal Wetland')
    elif i in STSBTF:
        df.append('South Texas Salt and Brackish Tidal Flats')
    elif i in TL:
        df.append('Tamaulipan Lomas')
    elif i in TPGRF:
        df.append('Tamaulipan Palm Grove Riparian Forest')
    elif i in TSL:
        df.append('Tamaulipan Saline Lake')
    elif i in Barren:
        df.append('Barren')
    elif i in Marsh:
        df.append('Marsh')
    elif i in NI:
        df.append('Native Invasive')
    elif i in STDGL:
        df.append('South Texas Disturbance Grassland')
    elif i in OW:
        df.append('Open Water')
    elif i in NNI:
        df.append('Non Native Invasive')
    elif i in TSTS:
        df.append('Tamaulipan Saline Thornscrub')
    elif i in CSTCFFW:
        df.append('Central and South Texas Coastal Fringe Forest and Woodland')
    elif i in TCGL:
        df.append('Tamaulipan Caliche Grassland')
    else:
        df.append('NaN')
    
        
    

In [8]:
RGV_ecoreg['Major_Ecoregion'] = df
RGV_ecoreg.tail(n=10)

OBJECTID  Veg_ID                                     CommonName  LULC  \
268960    268961    9411                            Urban Low Intensity    25   
268961    268962    9411                            Urban Low Intensity    25   
268962    268963    5605                Coastal: Sea Ox-eye Daisy Flats    11   
268963    268964    5617    Coastal: Salt and Brackish High Tidal Marsh    27   
268964    268965    6600                  South Texas: Wind Tidal Flats     1   
268965    268966    7107  South Texas: Sandy Mesquite Savanna Grassland    15   
268966    268967    9307                                      Row Crops     9   
268967    268968    9307                                      Row Crops     9   
268968    268969    9307                                      Row Crops     9   
268969    268970    9600                                     Open Water    21   

        Slope  Riparian   EcoClass_I                      EcoName  MoRAP_ID  \
268960      0         0  R083DY501TX     GRAY SANDY LOAM PE 19-31         0   
268961      0         0  R083DY501TX     GRAY SANDY LOAM PE 19-31         0   
268962      0         0  R150BY655TX  SANDY COASTAL FLAT PE 31-44         0   
268963      0         0  R150BY652TX         SALT MARSH  PE 31-44         0   
268964      0         0  R150BY651TX           SALT FLAT PE 31-44         0   
268965      0         0  R083CY463TX          LOAMY SAND PE 19-31         0   
268966      0         0  R083CY480TX          SANDY LOAM PE 19-31         0   
268967      0         0  R083DY504TX             LAKEBED PE 19-44         0   
268968      0         0  R150BY655TX  SANDY COASTAL FLAT PE 31-44         0   
268969      0         0  R083DY501TX     GRAY SANDY LOAM PE 19-31         0   

       US_L4CODE                                         US_L4NAME US_L3CODE  \
268960       34e                           Lower Rio Grande Valley        34   
268961       34e                           Lower Rio Grande Valley        34   
268962       34e                           Lower Rio Grande Valley        34   
268963       34i  Laguna Madre Barrier Islands and Coastal Marshes        34   
268964       34i  Laguna Madre Barrier Islands and Coastal Marshes        34   
268965       34d                                Coastal Sand Plain        34   
268966       34e                           Lower Rio Grande Valley        34   
268967       34e                           Lower Rio Grande Valley        34   
268968       34e                           Lower Rio Grande Valley        34   
268969       34e                           Lower Rio Grande Valley        34   

                         US_L3NAME      HUC12RNG   Shape_Leng     Shape_Area  \
268960  Western Gulf Coastal Plain  121102080400  4804.657264  101363.203592   
268961  Western Gulf Coastal Plain  121102080400   508.719023    5808.285643   
268962  Western Gulf Coastal Plain  121102080800   580.000000   13900.000000   
268963  Western Gulf Coastal Plain  121102080800  4066.640179  179933.064918   
268964  Western Gulf Coastal Plain  121102080800  1692.414009   23079.569882   
268965  Western Gulf Coastal Plain  121102070008  8715.483683  586649.222118   
268966  Western Gulf Coastal Plain  121102080300   859.361519   15110.197319   
268967  Western Gulf Coastal Plain  121102080300   597.590022   10608.125938   
268968  Western Gulf Coastal Plain  121102080300   778.370095   35481.894865   
268969  Western Gulf Coastal Plain  121102080300  3886.371293  328074.221869   

                                                 geometry  \
268960  POLYGON ((1684469 6920147.0001, 1684469 692013...   
268961  POLYGON ((1684639 6925007, 1684639 6924997, 16...   
268962  POLYGON ((1755440 6914483, 1755440 6914473, 17...   
268963  POLYGON ((1762070 6915313, 1762070 6915293, 17...   
268964  POLYGON ((1758870 6914803.0001, 1758870 691479...   
268965  (POLYGON ((1696421 6964752.4355, 1696389.86960...   
268966  POLYGON ((1705419 6914631.1078, 1705419 691462...

In [9]:
df2 = []

In [10]:

for i in Veg_ID:
    if i in TMDT:
        df2.append(0)
    elif i in TSG:
        df2.append(2)
    elif i in TCS:
        df2.append(3)
    elif i in TFP:
        df2.append(4)
    elif i in TR:
        df2.append(5)
    elif i in AOHR:
        df2.append(6)
    elif i in TCDW:
        df2.append(7)
    elif i in TSCP:
        df2.append(8)
    elif i in TCSBTM:
        df2.append(9)
    elif i in TCDCG:
        df2.append(10)
    elif i in CSTCFFW:
        df2.append(11)
    elif i in SECPIW:
        df2.append(12)
    elif i in STSBTF:
        df2.append(13)
    elif i in TL:
        df2.append(14)
    elif i in TPGRF:
        df2.append(15)
    elif i in TSL:
        df2.append(16)
    elif i in Barren:
        df2.append(17)
    elif i in Marsh:
        df2.append(18)
    elif i in NI:
        df2.append(19)
    elif i in STDGL:
        df2.append(20)
    elif i in OW:
        df2.append(21)
    elif i in NNI:
        df2.append(22)
    elif i in TSTS:
        df2.append(23)
    elif i in CSTCFFW:
        df2.append(24)
    elif i in TCGL:
        df2.append(25)
    else:
        df2.append('NaN')


In [11]:
RGV_ecoreg['Maj_ER'] = df2
RGV_ecoreg.tail(n=10)

OBJECTID  Veg_ID                                     CommonName  LULC  \
268960    268961    9411                            Urban Low Intensity    25   
268961    268962    9411                            Urban Low Intensity    25   
268962    268963    5605                Coastal: Sea Ox-eye Daisy Flats    11   
268963    268964    5617    Coastal: Salt and Brackish High Tidal Marsh    27   
268964    268965    6600                  South Texas: Wind Tidal Flats     1   
268965    268966    7107  South Texas: Sandy Mesquite Savanna Grassland    15   
268966    268967    9307                                      Row Crops     9   
268967    268968    9307                                      Row Crops     9   
268968    268969    9307                                      Row Crops     9   
268969    268970    9600                                     Open Water    21   

        Slope  Riparian   EcoClass_I                      EcoName  MoRAP_ID  \
268960      0         0  R083DY501TX     GRAY SANDY LOAM PE 19-31         0   
268961      0         0  R083DY501TX     GRAY SANDY LOAM PE 19-31         0   
268962      0         0  R150BY655TX  SANDY COASTAL FLAT PE 31-44         0   
268963      0         0  R150BY652TX         SALT MARSH  PE 31-44         0   
268964      0         0  R150BY651TX           SALT FLAT PE 31-44         0   
268965      0         0  R083CY463TX          LOAMY SAND PE 19-31         0   
268966      0         0  R083CY480TX          SANDY LOAM PE 19-31         0   
268967      0         0  R083DY504TX             LAKEBED PE 19-44         0   
268968      0         0  R150BY655TX  SANDY COASTAL FLAT PE 31-44         0   
268969      0         0  R083DY501TX     GRAY SANDY LOAM PE 19-31         0   

       US_L4CODE                                         US_L4NAME US_L3CODE  \
268960       34e                           Lower Rio Grande Valley        34   
268961       34e                           Lower Rio Grande Valley        34   
268962       34e                           Lower Rio Grande Valley        34   
268963       34i  Laguna Madre Barrier Islands and Coastal Marshes        34   
268964       34i  Laguna Madre Barrier Islands and Coastal Marshes        34   
268965       34d                                Coastal Sand Plain        34   
268966       34e                           Lower Rio Grande Valley        34   
268967       34e                           Lower Rio Grande Valley        34   
268968       34e                           Lower Rio Grande Valley        34   
268969       34e                           Lower Rio Grande Valley        34   

                         US_L3NAME      HUC12RNG   Shape_Leng     Shape_Area  \
268960  Western Gulf Coastal Plain  121102080400  4804.657264  101363.203592   
268961  Western Gulf Coastal Plain  121102080400   508.719023    5808.285643   
268962  Western Gulf Coastal Plain  121102080800   580.000000   13900.000000   
268963  Western Gulf Coastal Plain  121102080800  4066.640179  179933.064918   
268964  Western Gulf Coastal Plain  121102080800  1692.414009   23079.569882   
268965  Western Gulf Coastal Plain  121102070008  8715.483683  586649.222118   
268966  Western Gulf Coastal Plain  121102080300   859.361519   15110.197319   
268967  Western Gulf Coastal Plain  121102080300   597.590022   10608.125938   
268968  Western Gulf Coastal Plain  121102080300   778.370095   35481.894865   
268969  Western Gulf Coastal Plain  121102080300  3886.371293  328074.221869   

                                                 geometry  \
268960  POLYGON ((1684469 6920147.0001, 1684469 692013...   
268961  POLYGON ((1684639 6925007, 1684639 6924997, 16...   
268962  POLYGON ((1755440 6914483, 1755440 6914473, 17...   
268963  POLYGON ((1762070 6915313, 1762070 6915293, 17...   
268964  POLYGON ((1758870 6914803.0001, 1758870 691479...   
268965  (POLYGON ((1696421 6964752.4355, 1696389.86960...   
268966  POLYGON ((1705419 6914631.1078, 1705419 691462...

In [12]:
# find all of type 0
RGV_ecoreg.Maj_ER == 0

0          True
1          True
2          True
3          True
4          True
5          True
6          True
7          True
8          True
9          True
10         True
11         True
12         True
13         True
14         True
15         True
16         True
17         True
18         True
19         True
20         True
21         True
22         True
23         True
24         True
25         True
26         True
27         True
28         True
29         True
          ...  
268940    False
268941    False
268942    False
268943    False
268944    False
268945    False
268946    False
268947    False
268948    False
268949    False
268950    False
268951    False
268952    False
268953    False
268954    False
268955    False
268956    False
268957    False
268958    False
268959    False
268960    False
268961    False
268962    False
268963    False
268964    False
268965    False
268966    False
268967    False
268968    False
268969    False
Name: Maj_ER, Length: 26

In [13]:
RGV_ecoreg.Shape_Area.shape

(268970,)

In [14]:
RGV_ecoreg.Shape_Area[RGV_ecoreg.Maj_ER == 0]

0           2700.000000
1           1400.000000
2           1682.222500
3          36800.000000
4           1300.000000
5           8391.792000
6          80803.233499
7           1402.812584
8           1958.227567
9          11257.778388
10         11705.096000
11          4722.673017
12         13400.000000
13          4200.000000
14          2000.000000
15          2000.000000
16         28700.000000
17         10200.000000
18          3200.000000
19         47300.000000
20         11900.000000
21          9520.638000
22         54600.000000
23          2500.000000
24          6630.357836
25          3440.058438
26        117048.204546
27          7472.898993
28         24620.675428
29          2734.126000
              ...      
268005      5091.734834
268006     58507.252365
268007      4421.122329
268008     10670.576782
268009     26533.238553
268010      4400.000000
268011      5700.000000
268427     10775.172412
268428      2420.907132
268429      3395.173339
268430     14341

In [15]:
# get the areas for all of type 0
temp_areas = RGV_ecoreg.Shape_Area[RGV_ecoreg.Maj_ER == 0]
temp_areas.shape

(25726,)

temp_areas variable returned the column Shape_Area for all the rows that contained the value 0 in the column Maj_ER. It is aprox. 26,000 rows where as the RGV_ecoreg.Maj_ER is 269,000 rows. This is the magic of indexing.

In [16]:
# sum all of the areas we just found
total_area_0 = np.sum(temp_areas)
total_area_0


#I need to do this for values between 0 and 24. To do that I will need to use a for loop.

618710590.5234846

In [17]:
Maj_ER_Areas=np.arange(0,25)

In [18]:
Maj_ER_Areas

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [19]:
for ERn in np.arange(0,25):
    print(np.sum(RGV_ecoreg.Shape_Area[RGV_ecoreg.Maj_ER == ERn]))
    
#This looks like what I want but there are two values of zero. 
#Now I need to check value for 1 in my equation and see if I get zero.

618710590.5234846
0.0
2467283634.0686307
442216593.60378927
202253842.6212593
176496805.71520394
3562469831.6322064
14944765.930600151
535730598.01641876
259509859.10961932
727464989.6193082
66725479.02770927
8874321.72110065
376455038.98037183
68358006.63592342
649159.5606464
13775125.11699649
45532567.217426434
22858092.339831553
7572052.83865916
1569646004.4830456
172256020.67993057
1287346.7797249116
159185608.99921954
0.0


In [20]:
np.sum(RGV_ecoreg.Shape_Area[RGV_ecoreg.Maj_ER == 1])

#This result means my for loop worked, but it also menas there may be a problem with my data. 
#Now I need to check what ecoregion 1 represents

0.0

I skipped 1 in my first for loop...

In [21]:
df2 = []

In [22]:

for i in Veg_ID:
    if i in TMDT:
        df2.append(0)
    elif i in TSG:
        df2.append(1)
    elif i in TCS:
        df2.append(2)
    elif i in TFP:
        df2.append(3)
    elif i in TR:
        df2.append(4)
    elif i in AOHR:
        df2.append(5)
    elif i in TCDW:
        df2.append(6)
    elif i in TSCP:
        df2.append(7)
    elif i in TCSBTM:
        df2.append(8)
    elif i in TCDCG:
        df2.append(9)
    elif i in CSTCFFW:
        df2.append(10)
    elif i in SECPIW:
        df2.append(11)
    elif i in STSBTF:
        df2.append(12)
    elif i in TL:
        df2.append(13)
    elif i in TPGRF:
        df2.append(14)
    elif i in TSL:
        df2.append(15)
    elif i in Barren:
        df2.append(16)
    elif i in Marsh:
        df2.append(17)
    elif i in NI:
        df2.append(18)
    elif i in STDGL:
        df2.append(19)
    elif i in OW:
        df2.append(20)
    elif i in NNI:
        df2.append(21)
    elif i in TSTS:
        df2.append(22)
    elif i in CSTCFFW:
        df2.append(23)
    elif i in TCGL:
        df2.append(24)
    else:
        df2.append('NaN')


In [23]:
RGV_ecoreg['Maj_ER'] = df2
RGV_ecoreg.tail(n=10)

OBJECTID  Veg_ID                                     CommonName  LULC  \
268960    268961    9411                            Urban Low Intensity    25   
268961    268962    9411                            Urban Low Intensity    25   
268962    268963    5605                Coastal: Sea Ox-eye Daisy Flats    11   
268963    268964    5617    Coastal: Salt and Brackish High Tidal Marsh    27   
268964    268965    6600                  South Texas: Wind Tidal Flats     1   
268965    268966    7107  South Texas: Sandy Mesquite Savanna Grassland    15   
268966    268967    9307                                      Row Crops     9   
268967    268968    9307                                      Row Crops     9   
268968    268969    9307                                      Row Crops     9   
268969    268970    9600                                     Open Water    21   

        Slope  Riparian   EcoClass_I                      EcoName  MoRAP_ID  \
268960      0         0  R083DY501TX     GRAY SANDY LOAM PE 19-31         0   
268961      0         0  R083DY501TX     GRAY SANDY LOAM PE 19-31         0   
268962      0         0  R150BY655TX  SANDY COASTAL FLAT PE 31-44         0   
268963      0         0  R150BY652TX         SALT MARSH  PE 31-44         0   
268964      0         0  R150BY651TX           SALT FLAT PE 31-44         0   
268965      0         0  R083CY463TX          LOAMY SAND PE 19-31         0   
268966      0         0  R083CY480TX          SANDY LOAM PE 19-31         0   
268967      0         0  R083DY504TX             LAKEBED PE 19-44         0   
268968      0         0  R150BY655TX  SANDY COASTAL FLAT PE 31-44         0   
268969      0         0  R083DY501TX     GRAY SANDY LOAM PE 19-31         0   

       US_L4CODE                                         US_L4NAME US_L3CODE  \
268960       34e                           Lower Rio Grande Valley        34   
268961       34e                           Lower Rio Grande Valley        34   
268962       34e                           Lower Rio Grande Valley        34   
268963       34i  Laguna Madre Barrier Islands and Coastal Marshes        34   
268964       34i  Laguna Madre Barrier Islands and Coastal Marshes        34   
268965       34d                                Coastal Sand Plain        34   
268966       34e                           Lower Rio Grande Valley        34   
268967       34e                           Lower Rio Grande Valley        34   
268968       34e                           Lower Rio Grande Valley        34   
268969       34e                           Lower Rio Grande Valley        34   

                         US_L3NAME      HUC12RNG   Shape_Leng     Shape_Area  \
268960  Western Gulf Coastal Plain  121102080400  4804.657264  101363.203592   
268961  Western Gulf Coastal Plain  121102080400   508.719023    5808.285643   
268962  Western Gulf Coastal Plain  121102080800   580.000000   13900.000000   
268963  Western Gulf Coastal Plain  121102080800  4066.640179  179933.064918   
268964  Western Gulf Coastal Plain  121102080800  1692.414009   23079.569882   
268965  Western Gulf Coastal Plain  121102070008  8715.483683  586649.222118   
268966  Western Gulf Coastal Plain  121102080300   859.361519   15110.197319   
268967  Western Gulf Coastal Plain  121102080300   597.590022   10608.125938   
268968  Western Gulf Coastal Plain  121102080300   778.370095   35481.894865   
268969  Western Gulf Coastal Plain  121102080300  3886.371293  328074.221869   

                                                 geometry  \
268960  POLYGON ((1684469 6920147.0001, 1684469 692013...   
268961  POLYGON ((1684639 6925007, 1684639 6924997, 16...   
268962  POLYGON ((1755440 6914483, 1755440 6914473, 17...   
268963  POLYGON ((1762070 6915313, 1762070 6915293, 17...   
268964  POLYGON ((1758870 6914803.0001, 1758870 691479...   
268965  (POLYGON ((1696421 6964752.4355, 1696389.86960...   
268966  POLYGON ((1705419 6914631.1078, 1705419 691462...

In [24]:
Maj_ER_Areas=np.arange(0,25)
Maj_ER_Areas

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
for ERn in np.arange(0,25):
    print(np.sum(RGV_ecoreg.Shape_Area[RGV_ecoreg.Maj_ER == ERn]))
    
#23 is at zero, I wonder why..

618710590.5234846
2467283634.0686307
442216593.60378927
202253842.6212593
176496805.71520394
3562469831.6322064
14944765.930600151
535730598.01641876
259509859.10961932
727464989.6193082
66725479.02770927
8874321.72110065
376455038.98037183
68358006.63592342
649159.5606464
13775125.11699649
45532567.217426434
22858092.339831553
7572052.83865916
1569646004.4830456
172256020.67993057
1287346.7797249116
159185608.99921954
0.0
16259767.161396649


In [26]:
np.sum(RGV_ecoreg.Shape_Area[RGV_ecoreg.Maj_ER == 23])


0.0

In [27]:
RGV_ecoreg.Shape_Area[RGV_ecoreg.Maj_ER == 23]

Series([], Name: Shape_Area, dtype: float64)

In [28]:
RGV_ecoreg.Maj_ER == 23

#This is troubling. I think I need to check my variables with the PDF from the source of the Ecoregions shapefile again. 

0         False
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...  
268940    False
268941    False
268942    False
268943    False
268944    False
268945    False
268946    False
268947    False
268948    False
268949    False
268950    False
268951    False
268952    False
268953    False
268954    False
268955    False
268956    False
268957    False
268958    False
268959    False
268960    False
268961    False
268962    False
268963    False
268964    False
268965    False
268966    False
268967    False
268968    False
268969    False
Name: Maj_ER, Length: 26

In [29]:
Maj_ER_Areas

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
for ERn in np.arange(0,25):
    print(ERn)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [31]:
RGV_ecoreg['Veg_ID'].unique()


array([ 7004,  7005,  7103,  7104,  7105,  7107,  7204,  7205,  7207,
        7402,  7403,  7404,  7405,  7406,  7602,  7604,  7605,  7606,
        9000,  9007,  9104,  9106,  9124,  9187,  9304,  9307,  9410,
        9411,  9600, 10004, 10006, 10017,  7417,  2206,  2207,  5600,
        5605,  5617,  6307,  7407,  7802,  7804,  7805,  9107,  9128,
        9317,  5606,  5616,  6100,  6200,  6306,  6405,  6507,  6600,
        6610,  7305,  7306,  7307,  7502,  7700,  7707,  9204,  6806,
        7607,  6402,  6403,  6707,  9116], dtype=int64)

**Tamaulipan Mixed Deciduous Thornscrub - TMDT=[7004,7005]**
- 7004: South Texas: Clayey Mesquite Mixed Shrubland
- 7005: South Texas: Clayey Blackbrush Mixed Shrubland


        

**Tamaulipan Savanna Grassland - TSG=[7103,7104,7105,7107]**
- 7103: South Texas: Sandy Mesquite / Evergreen Woodland 
- 7104: South Texas: Sandy Mesquite Woodland and Shrubland
- 7105: South Texas: Sandy Mesquite Dense Shrubland
- 7107: South Texas: Sandy Mesquite Savanna Grassland

**Tamaulipan Calcareous Thornscrub - TCT=[7204,7205,7207]**
- 7204: South Texas: Shallow Shrubland
- 7205: South Texas: Shallow Dense Shrubland
- 7207: South Texas: Shallow Sparse Shrubland

**Tamaulipan Floodplain - TF=[7402,7403,7404,7405,7406,7417,7407]**
- 7402: South Texas: Floodplain Evergreen Forest and Woodland
- 7403: South Texas: Floodplain Mixed Deciduous / Evergreen Forest and Woodland
- 7404: South Texas: Floodplain Hardwood Forest and Woodland
- 7405: South Texas: Floodplain Evergreen Shrubland
- 7406: South Texas: Floodplain Deciduous Shrubland
- 7417: South Texas: Floodplain Herbaceous Wetland 
- 7407: South Texas: Floodplain Grassland

**Tamaulipan Ramadero - TR=[7602,7604,7605,7606,7607]**
- 7602: South Texas: Ramadero Evergreen Woodland
- 7604: South Texas: Ramadero Woodland
- 7605: South Texas: Ramadero Dense Shrubland
- 7606: South Texas: Ramadero Shrubland
- 7607: South Texas: Ramadero Herbaceous Wetland


**Mainly Natural Azonal Mapped Types - MNAMT=[9000,9007,9187,9600,9104,9106,9124,9107,9128,9116,9204]**
- 9000: Barren
- 9007: Marsh
- 9187: South Texas: Disturbance Grassland
- 9600: Open Water

  *Native invasive:*
    - 9104: Native Invasive: Deciduous Woodland
    - 9106: Native Invasive: Mesquite Shrubland
    - 9124: Native Invasive: Huisache Woodland or Shrubland
    - 9107: Native Invasive: Common Reed
    - 9128: Native Invasive: Pricklypear
    - 9116: Native Invasive: Baccharis Shrubland

  *Non-native Invasive:*
    - 9204: Non-native Invasive: Salt Cedar Shrubland

**Agricultural and other Human-related Mapped Types - AHRMT=[9304,9307,9410,9411,9600,9317]**
- 9304: Orchard
- 9307: Row Crops
- 9410: Urban High Intensity
- 9411: Urban Low Intensity
- 9600: Open Water
- 9317: Grass Farm

**Tamaulipan Closed Depression Wetland - TCDW=[10004,10006,10017]**
- 10004: South Texas: Pond and Laguna Woodland
- 10006: South Texas: Pond and Laguna Shrubland
- 10017: South Texas: Pondshore Herbaceous Vegetation (Should be 10007)

**Texas Saline Coastal Prairie - TSCP=[2206,2207]**
- 2206: Gulf Coast: Salty Shrubland
- 2207: Gulf Coast: Salty Prairie

**Texas Coast Salt and Brackish Tidal Marsh - TCSBTM=[5600,5605,5617,5606,5616]**
- 5600: Coastal: Tidal Flat
- 5605: Coastal: Sea Ox-eye Daisy Flats
- 5617: Coastal: Salt and Brackish High Tidal Marsh
- 5606: Coastal: Mangrove Shrubland
- 5616: Coastal: Salt and Brackish High Tidal Shrub Wetland

**Rio Grande Delta Thorn Woodland and Shrubland - RGDTWS=[7802,7804,7805]**
- 7802: Rio Grande Delta: Evergreen Thorn Woodland
- 7804: Rio Grande Delta: Deciduous Thorn Woodland and Shrubland
- 7805: Rio Grande Delta: Dense Shrubland

**Texas Coastal Beach - TCB=[6100]**
- 6100: Coastal: Beach

**Texas Coast Dune and Coastal Grassland - TCDCG=[6200,6306,6307]**
- 6200: Active Sand Dune
- 6306: Coastal and Sandsheet: Deep Sand Shrubland
- 6307: Coastal and Sandsheet: Dune and Coastal Grassland

**Southeastern Coastal Plain Interdunal Wetland - SCPIW=[6507]**
- 6507: Coastal and Sandsheet: Deep Sand Grasslands Swale Marsh 

**South Texas Salt and Brackish Tidal Flats - STSBTF=[6600,6610]**
- 6600: South Texas: Wind Tidal Flats
- 6610: South Texas: Algal Flats

**Tamaulipan Lomas - TL=[7305,7306,7307]**
- 7305: South Texas: Loma Evergreen Shrubland
- 7306: South Texas: Loma Deciduous Shrubland
- 7307: South Texas: Loma Grassland 

**Tamaulipan Palm Grove Riparian Forest - TPGRF=[7502]**
- 7502: South Texas: Palm Grove

**Tamaulipan Saline Lake - TSL=[7700,7707]**
- 7700: South Texas: Saline Lake Flats
- 7707: South Texas: Saline Lake Grassland

**Tamaulipan Saline Thornscrub - TST=[6806]**
- 6806: South Texas: Salty Thornscrub

**Central and South Texas Coastal Fringe Forest and Woodland - CSTCFFW=[6402,6403,6405]**
- 6402: Coastal and Sandsheet: Deep Sand Live Oak Forest and Woodland
- 6403: Coastal and Sandsheet: Deep Sand Live Oak - Mesquite Woodland
- 6405: Coastal and Sandsheet: Deep Sand Live Oak Shrubland


**Tamaulipan Caliche Grassland - TCG=[6707]**
- 6707: South Texas: Caliche Grassland

#These two were not in a cataegory, but I put them in one.

**UNK**
- 10017: South Texas: Pondshore Herbaceous Vegetation
- 7607: South Texas: Ramadero Herbaceous Wetland


In [32]:
#I want to know why there are two UNK values

RGV_ecoreg.CommonName[RGV_ecoreg.Veg_ID == 7607]

#I put this in the Tamaulipan Ramadero category

162184    South Texas: Ramadero Herbaceous Wetland
Name: CommonName, dtype: object

In [33]:
RGV_ecoreg.CommonName[RGV_ecoreg.Veg_ID == 10017]

#I put South Texas: Pondshore Herbaceous Vegetation into Ctrl+F in the PDF
#It found South Texas: Pondshore Herbaceous Vegetation (10007)
#I think it was a typo in the attribute table. 
#At least its a consistent typo.

5497      South Texas: Pondshore Herbaceous Vegetation
173883    South Texas: Pondshore Herbaceous Vegetation
173884    South Texas: Pondshore Herbaceous Vegetation
173885    South Texas: Pondshore Herbaceous Vegetation
173886    South Texas: Pondshore Herbaceous Vegetation
173887    South Texas: Pondshore Herbaceous Vegetation
Name: CommonName, dtype: object

In [35]:
TMDT=[7004,7005]
TSG=[7103,7104,7105,7107]
TCT=[7204,7205,7207]
TF=[7402,7403,7404,7405,7406,7417,7407]
TR=[7602,7604,7605,7606,7607]
MNAMT=[9000,9007,9187,9600,9104,9106,9124,9107,9128,9116,9204]
AHRMT=[9304,9307,9410,9411,9600,9317]
TCDW=[10004,10006,10017]
TSCP=[2206,2207]
TCSBTM=[5600,5605,5617,5606,5616]
RGDTWS=[7802,7804,7805]
TCB=[6100]
TCDCG=[6200,6306,6307]
SCPIW=[6507]
STSBTF=[6600,6610]
TL=[7305,7306,7307]
TPGRF=[7502]
TSL=[7700,7707]
TST=[6806]
CSTCFFW=[6402,6403,6405]
TCG=[6707]

In [43]:
df = []
Veg_ID = RGV_ecoreg['Veg_ID']

In [44]:
for i in Veg_ID:
    if i in TMDT:
        df.append('Tamaulipan Mixed Deciduous Thornscrub')
    elif i in TSG:
        df.append('Tamaulipan Savanna Grassland')
    elif i in TCT:
        df.append('Tamaulipan Calcareous Thornscrub')
    elif i in TF:
        df.append('Tamaulipan Floodplain')
    elif i in TR:
        df.append('Tamulipan Ramadero')
    elif i in MNAMT:
        df.append('Mainly Natural Azonal Mapped Types') 
    elif i in AHRMT:
        df.append('Agricultural and other Human-related Mapped Types')
    elif i in TCDW:
        df.append('Tamaulipan Closed Depression Wetland')
    elif i in TSCP:
        df.append('Texas Saline Coastal Prairie')
    elif i in TCSBTM:
        df.append('Texas Coast Salt and Brackish Tidal Marsh')
    elif i in RGDTWS:
        df.append('Rio Grande Delta Thorn Woodland and Shrubland')    
    elif i in TCB:
        df.append('Texas Coastal Beach')          
    elif i in TCDCG:
        df.append('Texas Coast Dune and Coastal Grassland') 
    elif i in SCPIW:
        df.append('Southeastern Coastal Plain Interdunal Wetland')        
    elif i in STSBTF:
        df.append('South Texas Salt and Brackish Tidal Flats')        
    elif i in TL:
        df.append('Tamaulipan Lomas')
    elif i in TPGRF:
        df.append('Tamaulipan Palm Grove Riparian Forest')
    elif i in TSL:
        df.append('Tamaulipan Saline Lake')        
    elif i in TST:
        df.append('Tamaulipan Saline Thornscrub')      
    elif i in CSTCFFW:
        df.append('Central and South Texas Coastal Fringe Forest and Woodland')
    elif i in TCG:
        df.append('Tamaulipan Caliche Grassland')
    else:
        df.append('NaN')

In [45]:
RGV_ecoreg['Major_Ecoregion'] = df
RGV_ecoreg.tail()

OBJECTID  Veg_ID                                     CommonName  LULC  \
268965    268966    7107  South Texas: Sandy Mesquite Savanna Grassland    15   
268966    268967    9307                                      Row Crops     9   
268967    268968    9307                                      Row Crops     9   
268968    268969    9307                                      Row Crops     9   
268969    268970    9600                                     Open Water    21   

        Slope  Riparian   EcoClass_I                      EcoName  MoRAP_ID  \
268965      0         0  R083CY463TX          LOAMY SAND PE 19-31         0   
268966      0         0  R083CY480TX          SANDY LOAM PE 19-31         0   
268967      0         0  R083DY504TX             LAKEBED PE 19-44         0   
268968      0         0  R150BY655TX  SANDY COASTAL FLAT PE 31-44         0   
268969      0         0  R083DY501TX     GRAY SANDY LOAM PE 19-31         0   

       US_L4CODE                US_L4NAME US_L3CODE  \
268965       34d       Coastal Sand Plain        34   
268966       34e  Lower Rio Grande Valley        34   
268967       34e  Lower Rio Grande Valley        34   
268968       34e  Lower Rio Grande Valley        34   
268969       34e  Lower Rio Grande Valley        34   

                         US_L3NAME      HUC12RNG   Shape_Leng     Shape_Area  \
268965  Western Gulf Coastal Plain  121102070008  8715.483683  586649.222118   
268966  Western Gulf Coastal Plain  121102080300   859.361519   15110.197319   
268967  Western Gulf Coastal Plain  121102080300   597.590022   10608.125938   
268968  Western Gulf Coastal Plain  121102080300   778.370095   35481.894865   
268969  Western Gulf Coastal Plain  121102080300  3886.371293  328074.221869   

                                                 geometry  \
268965  (POLYGON ((1696421 6964752.4355, 1696389.86960...   
268966  POLYGON ((1705419 6914631.1078, 1705419 691462...   
268967  POLYGON ((1724270 6914509.9858, 1724270 691450...   
268968  POLYGON ((1732782 6914658, 1732782 6914638, 17...   
268969  POLYGON ((1686069 6915037, 1686069 6915027, 16...   

                                          Major_Ecoregion Maj_ER  
268965                       Tamaulipan Savanna Grassland      1  
268966  Agricultural and other Human-related Mapped Types      5  
268967  Agricultural and other Human-related Mapped Types      5  
268968  Agricultural and other Human-related Mapped Types      5  
268969                 Mainly Natural Azonal Mapped Types     20

In [75]:
df2 = []

In [76]:
for i in Veg_ID:
    if i in TMDT:
        df2.append(0)
    elif i in TSG:
        df2.append(1)
    elif i in TCT:
        df2.append(2)
    elif i in TF:
        df2.append(3)
    elif i in TR:
        df2.append(4)
    elif i in MNAMT:
        df2.append(5)
    elif i in AHRMT:
        df2.append(6)
    elif i in TCDW:
        df2.append(7)
    elif i in TSCP:
        df2.append(8)
    elif i in TCSBTM:
        df2.append(9)
    elif i in RGDTWS:
        df2.append(10)
    elif i in TCB:
        df2.append(11)
    elif i in TCDCG:
        df2.append(12)
    elif i in SCPIW:
        df2.append(13)
    elif i in STSBTF:
        df2.append(14)
    elif i in TL:
        df2.append(15)
    elif i in TPGRF:
        df2.append(16)
    elif i in TSL:
        df2.append(17)
    elif i in TST:
        df2.append(18)
    elif i in CSTCFFW:
        df2.append(19)
    elif i in TCG:
        df2.append(20)      
    else:
        df2.append('NaN')


In [77]:
RGV_ecoreg['Maj_ER'] = df2
RGV_ecoreg.tail(n=10)

OBJECTID  Veg_ID                                     CommonName  LULC  \
268960    268961    9411                            Urban Low Intensity    25   
268961    268962    9411                            Urban Low Intensity    25   
268962    268963    5605                Coastal: Sea Ox-eye Daisy Flats    11   
268963    268964    5617    Coastal: Salt and Brackish High Tidal Marsh    27   
268964    268965    6600                  South Texas: Wind Tidal Flats     1   
268965    268966    7107  South Texas: Sandy Mesquite Savanna Grassland    15   
268966    268967    9307                                      Row Crops     9   
268967    268968    9307                                      Row Crops     9   
268968    268969    9307                                      Row Crops     9   
268969    268970    9600                                     Open Water    21   

        Slope  Riparian   EcoClass_I                      EcoName  MoRAP_ID  \
268960      0         0  R083DY501TX     GRAY SANDY LOAM PE 19-31         0   
268961      0         0  R083DY501TX     GRAY SANDY LOAM PE 19-31         0   
268962      0         0  R150BY655TX  SANDY COASTAL FLAT PE 31-44         0   
268963      0         0  R150BY652TX         SALT MARSH  PE 31-44         0   
268964      0         0  R150BY651TX           SALT FLAT PE 31-44         0   
268965      0         0  R083CY463TX          LOAMY SAND PE 19-31         0   
268966      0         0  R083CY480TX          SANDY LOAM PE 19-31         0   
268967      0         0  R083DY504TX             LAKEBED PE 19-44         0   
268968      0         0  R150BY655TX  SANDY COASTAL FLAT PE 31-44         0   
268969      0         0  R083DY501TX     GRAY SANDY LOAM PE 19-31         0   

       US_L4CODE                                         US_L4NAME US_L3CODE  \
268960       34e                           Lower Rio Grande Valley        34   
268961       34e                           Lower Rio Grande Valley        34   
268962       34e                           Lower Rio Grande Valley        34   
268963       34i  Laguna Madre Barrier Islands and Coastal Marshes        34   
268964       34i  Laguna Madre Barrier Islands and Coastal Marshes        34   
268965       34d                                Coastal Sand Plain        34   
268966       34e                           Lower Rio Grande Valley        34   
268967       34e                           Lower Rio Grande Valley        34   
268968       34e                           Lower Rio Grande Valley        34   
268969       34e                           Lower Rio Grande Valley        34   

                         US_L3NAME      HUC12RNG   Shape_Leng     Shape_Area  \
268960  Western Gulf Coastal Plain  121102080400  4804.657264  101363.203592   
268961  Western Gulf Coastal Plain  121102080400   508.719023    5808.285643   
268962  Western Gulf Coastal Plain  121102080800   580.000000   13900.000000   
268963  Western Gulf Coastal Plain  121102080800  4066.640179  179933.064918   
268964  Western Gulf Coastal Plain  121102080800  1692.414009   23079.569882   
268965  Western Gulf Coastal Plain  121102070008  8715.483683  586649.222118   
268966  Western Gulf Coastal Plain  121102080300   859.361519   15110.197319   
268967  Western Gulf Coastal Plain  121102080300   597.590022   10608.125938   
268968  Western Gulf Coastal Plain  121102080300   778.370095   35481.894865   
268969  Western Gulf Coastal Plain  121102080300  3886.371293  328074.221869   

                                                 geometry  \
268960  POLYGON ((1684469 6920147.0001, 1684469 692013...   
268961  POLYGON ((1684639 6925007, 1684639 6924997, 16...   
268962  POLYGON ((1755440 6914483, 1755440 6914473, 17...   
268963  POLYGON ((1762070 6915313, 1762070 6915293, 17...   
268964  POLYGON ((1758870 6914803.0001, 1758870 691479...   
268965  (POLYGON ((1696421 6964752.4355, 1696389.86960...   
268966  POLYGON ((1705419 6914631.1078, 1705419 691462...

In [50]:
Maj_ER_Areas=np.arange(0,21)
Maj_ER_Areas

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [72]:
for ERn in np.arange(0,21):
    print(np.sum(RGV_ecoreg.Shape_Area[RGV_ecoreg.Maj_ER == ERn]))
    

618710590.5234846
2467283634.0686307
442216593.60378927
202253842.6212593
176501205.71520394
1821777320.1111965
3570055490.8441744
14993065.930600151
535730598.01641876
259509859.10961932
23215181.89602481
1637675.184440527
727464989.6193082
8874321.72110065
376455038.98037183
68358006.63592342
649159.5606464
13775125.11699649
159185608.99921954
107548892.23097286
16259767.161396649


In [73]:
np.sum(RGV_ecoreg.Shape_Area)

11612455967.650782

In [74]:
1.618710590.5234846
2.+2467283634.0686307
3.+442216593.60378927
4.+202253842.6212593
5.+176501205.71520394
6.+1821777320.1111965
7.+3570055490.8441744
8.+14993065.930600151
9.+535730598.01641876
10.+259509859.10961932
11.+23215181.89602481
12.+1637675.184440527
13+727464989.6193082
14.+8874321.72110065
15.+376455038.98037183
16.+68358006.63592342
17.+649159.5606464
18.+13775125.11699649
19.+159185608.99921954
20+107548892.23097286
21.+16259767.161396649



16259767.161396649

The sum of the shape areas should have been the same as the sum of the Major Ecoregions. It wasn't. This is probably because there was shapes with NaN that weren't add to the total

In [60]:
RGV_ecoreg.Maj_ER == 'NaN'


C:\Users\Bridgett\Anaconda3\lib\site-packages\pandas\core\ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)


0         False
1         False
2         False
3         False
4         False
5         False
6         False
7         False
8         False
9         False
10        False
11        False
12        False
13        False
14        False
15        False
16        False
17        False
18        False
19        False
20        False
21        False
22        False
23        False
24        False
25        False
26        False
27        False
28        False
29        False
          ...  
268940    False
268941    False
268942    False
268943    False
268944    False
268945    False
268946    False
268947    False
268948    False
268949    False
268950    False
268951    False
268952    False
268953    False
268954    False
268955    False
268956    False
268957    False
268958    False
268959    False
268960    False
268961    False
268962    False
268963    False
268964    False
268965    False
268966    False
268967    False
268968    False
268969    False
Name: Maj_ER, Length: 26

In [64]:
RGV_ecoreg.Shape_Area[RGV_ecoreg.Maj_ER == 0]

0           2700.000000
1           1400.000000
2           1682.222500
3          36800.000000
4           1300.000000
5           8391.792000
6          80803.233499
7           1402.812584
8           1958.227567
9          11257.778388
10         11705.096000
11          4722.673017
12         13400.000000
13          4200.000000
14          2000.000000
15          2000.000000
16         28700.000000
17         10200.000000
18          3200.000000
19         47300.000000
20         11900.000000
21          9520.638000
22         54600.000000
23          2500.000000
24          6630.357836
25          3440.058438
26        117048.204546
27          7472.898993
28         24620.675428
29          2734.126000
              ...      
268005      5091.734834
268006     58507.252365
268007      4421.122329
268008     10670.576782
268009     26533.238553
268010      4400.000000
268011      5700.000000
268427     10775.172412
268428      2420.907132
268429      3395.173339
268430     14341

In [66]:
RGV_ecoreg.Shape_Area[RGV_ecoreg.Maj_ER == 'NaN']

C:\Users\Bridgett\Anaconda3\lib\site-packages\pandas\core\ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)


Series([], Name: Shape_Area, dtype: float64)

I will switch NaN to a number and try to index it like that. 

In [79]:
df2 = []

In [80]:
for i in Veg_ID:
    if i in TMDT:
        df2.append(0)
    elif i in TSG:
        df2.append(1)
    elif i in TCT:
        df2.append(2)
    elif i in TF:
        df2.append(3)
    elif i in TR:
        df2.append(4)
    elif i in MNAMT:
        df2.append(5)
    elif i in AHRMT:
        df2.append(6)
    elif i in TCDW:
        df2.append(7)
    elif i in TSCP:
        df2.append(8)
    elif i in TCSBTM:
        df2.append(9)
    elif i in RGDTWS:
        df2.append(10)
    elif i in TCB:
        df2.append(11)
    elif i in TCDCG:
        df2.append(12)
    elif i in SCPIW:
        df2.append(13)
    elif i in STSBTF:
        df2.append(14)
    elif i in TL:
        df2.append(15)
    elif i in TPGRF:
        df2.append(16)
    elif i in TSL:
        df2.append(17)
    elif i in TST:
        df2.append(18)
    elif i in CSTCFFW:
        df2.append(19)
    elif i in TCG:
        df2.append(20)      
    else:
        df2.append(12345)

In [81]:
RGV_ecoreg['Maj_ER'] = df2
RGV_ecoreg.tail(n=10)

OBJECTID  Veg_ID                                     CommonName  LULC  \
268960    268961    9411                            Urban Low Intensity    25   
268961    268962    9411                            Urban Low Intensity    25   
268962    268963    5605                Coastal: Sea Ox-eye Daisy Flats    11   
268963    268964    5617    Coastal: Salt and Brackish High Tidal Marsh    27   
268964    268965    6600                  South Texas: Wind Tidal Flats     1   
268965    268966    7107  South Texas: Sandy Mesquite Savanna Grassland    15   
268966    268967    9307                                      Row Crops     9   
268967    268968    9307                                      Row Crops     9   
268968    268969    9307                                      Row Crops     9   
268969    268970    9600                                     Open Water    21   

        Slope  Riparian   EcoClass_I                      EcoName  MoRAP_ID  \
268960      0         0  R083DY501TX     GRAY SANDY LOAM PE 19-31         0   
268961      0         0  R083DY501TX     GRAY SANDY LOAM PE 19-31         0   
268962      0         0  R150BY655TX  SANDY COASTAL FLAT PE 31-44         0   
268963      0         0  R150BY652TX         SALT MARSH  PE 31-44         0   
268964      0         0  R150BY651TX           SALT FLAT PE 31-44         0   
268965      0         0  R083CY463TX          LOAMY SAND PE 19-31         0   
268966      0         0  R083CY480TX          SANDY LOAM PE 19-31         0   
268967      0         0  R083DY504TX             LAKEBED PE 19-44         0   
268968      0         0  R150BY655TX  SANDY COASTAL FLAT PE 31-44         0   
268969      0         0  R083DY501TX     GRAY SANDY LOAM PE 19-31         0   

       US_L4CODE                                         US_L4NAME US_L3CODE  \
268960       34e                           Lower Rio Grande Valley        34   
268961       34e                           Lower Rio Grande Valley        34   
268962       34e                           Lower Rio Grande Valley        34   
268963       34i  Laguna Madre Barrier Islands and Coastal Marshes        34   
268964       34i  Laguna Madre Barrier Islands and Coastal Marshes        34   
268965       34d                                Coastal Sand Plain        34   
268966       34e                           Lower Rio Grande Valley        34   
268967       34e                           Lower Rio Grande Valley        34   
268968       34e                           Lower Rio Grande Valley        34   
268969       34e                           Lower Rio Grande Valley        34   

                         US_L3NAME      HUC12RNG   Shape_Leng     Shape_Area  \
268960  Western Gulf Coastal Plain  121102080400  4804.657264  101363.203592   
268961  Western Gulf Coastal Plain  121102080400   508.719023    5808.285643   
268962  Western Gulf Coastal Plain  121102080800   580.000000   13900.000000   
268963  Western Gulf Coastal Plain  121102080800  4066.640179  179933.064918   
268964  Western Gulf Coastal Plain  121102080800  1692.414009   23079.569882   
268965  Western Gulf Coastal Plain  121102070008  8715.483683  586649.222118   
268966  Western Gulf Coastal Plain  121102080300   859.361519   15110.197319   
268967  Western Gulf Coastal Plain  121102080300   597.590022   10608.125938   
268968  Western Gulf Coastal Plain  121102080300   778.370095   35481.894865   
268969  Western Gulf Coastal Plain  121102080300  3886.371293  328074.221869   

                                                 geometry  \
268960  POLYGON ((1684469 6920147.0001, 1684469 692013...   
268961  POLYGON ((1684639 6925007, 1684639 6924997, 16...   
268962  POLYGON ((1755440 6914483, 1755440 6914473, 17...   
268963  POLYGON ((1762070 6915313, 1762070 6915293, 17...   
268964  POLYGON ((1758870 6914803.0001, 1758870 691479...   
268965  (POLYGON ((1696421 6964752.4355, 1696389.86960...   
268966  POLYGON ((1705419 6914631.1078, 1705419 691462...

In [83]:
x=RGV_ecoreg.Shape_Area[RGV_ecoreg.Maj_ER == 12345]

In [84]:
x.shape

(0,)

Since there are no rows that equal to 12345, the shape is zero. This means the for loop worked, but I need to approach the problem of the areas not equalling each other in another way.
